const db=require('../config/db');
const {buildError}=require('../utils/apiError');
const {amountFromCents,getCargoFinancialSnapshot,getServerNow}=require('./financeService');
const {ELIGIBILITY_TARGETS,evaluateRequirement,validateEligibilityRequirement}=require('./eligibilityEvaluatorRegistry');
const stateKey=async(executor,workflow,value)=>(await executor.query('SELECT state_key FROM workflow_states WHERE workflow_key=$1 AND storage_value=$2',[workflow,value])).rows[0]?.state_key||null;
const activeDispatch=async(executor,cargoId,lock=false)=>(await executor.query(`SELECT * FROM dispatch_requests WHERE cargo_id=$1 AND status='Approved' AND gate_released_at IS NULL ORDER BY decided_at DESC NULLS LAST,id DESC LIMIT 1 ${lock?'FOR UPDATE':''}`,[cargoId])).rows[0]||null;
const evaluateEligibility=async({target,cargo,executor=db,at=null,emergencyReference=null,lock=false})=>{
 const now=at||await getServerNow(executor); const policyResult=await executor.query(`SELECT * FROM eligibility_policies WHERE target=$1 AND active AND configuration_status='ready' AND effective_from<=$2 ORDER BY effective_from DESC,revision DESC LIMIT 2`,[target,now]);
 if(policyResult.rowCount!==1)throw buildError('Eligibility policy is missing or ambiguous.',409,null,target==='dispatch_request'?'DISPATCH_POLICY_NOT_READY':'GATE_POLICY_NOT_READY'); const policy=policyResult.rows[0];
 const managementRequirement=target.includes('gate_release')?evaluateRequirement(target,'management_release_authorization',{cargo},{}):null;
 if(managementRequirement&&!managementRequirement.passed){
  const requirement={evaluator_key:'management_release_authorization',...managementRequirement};
  return {eligible:false,policy_key:policy.policy_key,revision:policy.revision,calculation_time:now,outstanding_amount:'0.00',requirements:[requirement],blocked_requirements:[requirement],dispatch_request:null,emergency_authorization:null};
 }
 const finance=target==='normal_gate_release'?await getCargoFinancialSnapshot({cargoId:cargo.id,at:now,executor}):null; const dispatch=target==='normal_gate_release'?await activeDispatch(executor,cargo.id,lock):null;
 let emergency=null;if(target==='emergency_gate_release'&&emergencyReference) emergency=(await executor.query(`SELECT * FROM emergency_release_requests WHERE public_reference=$1 AND cargo_id=$2 AND status='Approved' AND consumed_at IS NULL FOR UPDATE`,[emergencyReference,cargo.id])).rows[0]||null;
 const context={cargo,registration_state_key:await stateKey(executor,'cargo_registration',cargo.registration_status),placement_state_key:await stateKey(executor,'cargo_placement',cargo.placement_status),customs_state_key:cargo.customs_status_key,release_state_key:cargo.gate_out_status==='Not Released'?'not_released':'released',outstanding_cents:finance?.outstanding_cents||0n,outstanding_amount:finance?amountFromCents(finance.outstanding_cents):'0.00',dispatch_request:dispatch,emergency_authorization:emergency};
 const requirements=(await executor.query(`SELECT * FROM eligibility_policy_requirements WHERE policy_key=$1 AND revision=$2 AND is_required ORDER BY priority,id`,[policy.policy_key,policy.revision])).rows.map(r=>({evaluator_key:r.evaluator_key,...evaluateRequirement(target,r.evaluator_key,context,r.parameters)}));
 return {eligible:requirements.every(r=>r.passed),policy_key:policy.policy_key,revision:policy.revision,calculation_time:now,outstanding_amount:context.outstanding_amount,requirements,blocked_requirements:requirements.filter(r=>!r.passed),dispatch_request:dispatch,emergency_authorization:emergency};
};
const validateEligibilityPolicies=async(executor=db)=>{const rows=(await executor.query(`SELECT p.policy_key,p.revision,p.target,p.configuration_status,r.evaluator_key,r.parameters,perm.permission_key FROM eligibility_policies p LEFT JOIN eligibility_policy_requirements r ON r.policy_key=p.policy_key AND r.revision=p.revision AND r.is_required LEFT JOIN permissions perm ON perm.permission_key=CASE p.target WHEN 'dispatch_request' THEN 'dispatch.requests.create' WHEN 'normal_gate_release' THEN 'gate.gate_out.confirm' ELSE 'gate.emergency_release.request' END WHERE p.active`)).rows;const issues=[];for(const target of ELIGIBILITY_TARGETS){const keys=[...new Set(rows.filter(r=>r.target===target).map(r=>r.policy_key))];if(keys.length===0)issues.push({code:'ELIGIBILITY_POLICY_MISSING',target});else if(keys.length!==1)issues.push({code:'ELIGIBILITY_POLICY_AMBIGUOUS',target});}for(const r of rows){if(!ELIGIBILITY_TARGETS.includes(r.target)||r.configuration_status!=='ready'||!r.evaluator_key||validateEligibilityRequirement(r.target,r.evaluator_key,r.parameters).length||!r.permission_key)issues.push({code:'ELIGIBILITY_POLICY_INVALID',policy_key:r.policy_key,target:r.target});}return{ready:issues.length===0,issues,policies:[...new Set(rows.map(r=>r.policy_key))]};};
module.exports={activeDispatch,evaluateEligibility,validateEligibilityPolicies};
