const db = require("../config/db");
const { parseFilters } = require("./reportService");

const period = (column) => `($1::date IS NULL OR ${column} >= $1::date) AND ($2::date IS NULL OR ${column} < $2::date + INTERVAL '1 day')`;
const paging = (f) => [f.dateFrom, f.dateTo, f.pageSize, (f.page - 1) * f.pageSize, `%${f.search}%`];
const pagination = (f, total) => ({ page: f.page, pageSize: f.pageSize, total: Number(total || 0), totalPages: Math.ceil(Number(total || 0) / f.pageSize) });
const table = (key, title, columns, rows, f, total) => ({ key, title, columns, rows, pagination: pagination(f, total) });

async function finance(filters, executor) {
  const v = paging(filters);
  const [summary, revenue, types, statuses, balances, invoiceCount, invoices, payments] = await Promise.all([
    executor.query(`SELECT COALESCE(SUM(total_amount) FILTER(WHERE status<>'Cancelled'),0)::numeric total_invoiced,COALESCE((SELECT SUM(amount_received) FROM payments WHERE status='Confirmed' AND reconciliation_status='MATCHED' AND ${period("COALESCE(verified_at,created_at)")}),0)::numeric verified_paid,COALESCE(SUM(outstanding_balance) FILTER(WHERE status<>'Cancelled'),0)::numeric outstanding,COUNT(*) FILTER(WHERE payment_status='Partially Paid')::int partially_paid,COALESCE((SELECT COUNT(*) FROM payments WHERE status IN ('Gateway Failed','Gateway Exception') OR reconciliation_status<>'MATCHED'),0)::int failed_unmatched FROM invoices WHERE ${period("created_at")}`, [v[0],v[1]]),
    executor.query(`SELECT DATE(COALESCE(verified_at,created_at)) period,COALESCE(SUM(amount_received),0)::numeric value FROM payments WHERE status='Confirmed' AND reconciliation_status='MATCHED' AND ${period("COALESCE(verified_at,created_at)")} GROUP BY 1 ORDER BY 1`,v.slice(0,2)),
    executor.query(`SELECT c.cargo_type label,COALESCE(SUM(p.amount_received),0)::numeric value FROM payments p JOIN invoices i ON i.id=p.invoice_id JOIN cargo c ON c.id=i.cargo_id WHERE p.status='Confirmed' AND p.reconciliation_status='MATCHED' AND ${period("COALESCE(p.verified_at,p.created_at)")} GROUP BY c.cargo_type ORDER BY value DESC`,v.slice(0,2)),
    executor.query(`SELECT payment_status label,COUNT(*)::int value FROM invoices WHERE status<>'Cancelled' AND ${period("created_at")} GROUP BY payment_status ORDER BY label`,v.slice(0,2)),
    executor.query(`SELECT DATE(created_at) period,COALESCE(SUM(outstanding_balance) FILTER(WHERE status<>'Cancelled'),0)::numeric value FROM invoices WHERE ${period("created_at")} GROUP BY 1 ORDER BY 1`,v.slice(0,2)),
    executor.query(`SELECT COUNT(*) total FROM invoices i JOIN cargo c ON c.id=i.cargo_id WHERE $3::int>0 AND $4::int>=0 AND ${period("i.created_at")} AND ($5='%%' OR i.public_invoice_number ILIKE $5 OR c.cargo_id ILIKE $5 OR i.payment_reference ILIKE $5)`,v),
    executor.query(`SELECT i.public_invoice_number invoice_reference,c.cargo_id cargo_reference,i.total_amount invoice_amount,i.amount_paid,i.outstanding_balance outstanding_amount,i.status invoice_status,i.issued_at issue_date,i.payment_reference FROM invoices i JOIN cargo c ON c.id=i.cargo_id WHERE ${period("i.created_at")} AND ($5='%%' OR i.public_invoice_number ILIKE $5 OR c.cargo_id ILIKE $5 OR i.payment_reference ILIKE $5) ORDER BY i.created_at DESC LIMIT $3 OFFSET $4`,v),
    executor.query(`SELECT p.payment_reference wms_payment_reference,p.gateway_transaction_id flutterwave_charge_reference,c.cargo_id cargo_reference,i.public_invoice_number invoice_reference,p.expected_amount,p.amount_received verified_paid_amount,p.gateway_status provider_status,p.reconciliation_status,COALESCE(p.verified_at,p.created_at) settled_timestamp FROM payments p JOIN invoices i ON i.id=p.invoice_id JOIN cargo c ON c.id=i.cargo_id WHERE ${period("p.created_at")} AND ($5='%%' OR p.payment_reference ILIKE $5 OR p.gateway_transaction_id ILIKE $5 OR c.cargo_id ILIKE $5 OR i.public_invoice_number ILIKE $5) ORDER BY p.created_at DESC LIMIT $3 OFFSET $4`,v)
  ]);
  return { kpis: summary.rows[0], charts:[{title:"Revenue Over Time",type:"line",data:revenue.rows},{title:"Revenue by Cargo Type",type:"bar",data:types.rows},{title:"Payment Status Distribution",type:"pie",data:statuses.rows},{title:"Outstanding Balance Over Time",type:"line",data:balances.rows}], tables:[table("invoices","Invoice Report",Object.keys(invoices.rows[0]||{}),invoices.rows,filters,invoiceCount.rows[0].total),table("payments","Payment / Reconciliation",Object.keys(payments.rows[0]||{}),payments.rows,filters,payments.rowCount)] };
}

async function auditor(filters, executor) {
  const v=paging(filters); const extra=[filters.role||null,filters.module||null,filters.action||null,filters.userId||null];
  const where=`$3::int>0 AND $4::int>=0 AND ${period("a.created_at")} AND ($5='%%' OR a.description ILIKE $5 OR a.action ILIKE $5 OR a.metadata::text ILIKE $5) AND ($6::text IS NULL OR r.role_key=$6) AND ($7::text IS NULL OR a.module=$7) AND ($8::text IS NULL OR a.action=$8) AND ($9::int IS NULL OR a.user_id=$9)`;
  const values=[...v,...extra];
  const [summary,time,modules,roles,actions,count,rows,options]=await Promise.all([
    executor.query(`SELECT COUNT(*)::int total_audit_events,COUNT(*) FILTER(WHERE user_id IS NOT NULL)::int user_actions,COUNT(*) FILTER(WHERE module ILIKE ANY(ARRAY['%finance%','%payment%','%invoice%','%tariff%']))::int financial_events,COUNT(*) FILTER(WHERE module ILIKE '%configuration%' OR action ILIKE '%CONFIG%')::int configuration_changes,COUNT(*) FILTER(WHERE module ILIKE ANY(ARRAY['%auth%','%session%','%security%']) OR action ILIKE ANY(ARRAY['%LOGIN%','%LOGOUT%','%PASSWORD%']))::int security_events FROM audit_logs a LEFT JOIN roles r ON r.id=a.role_id_at_action WHERE ${where}`,values),
    executor.query(`SELECT DATE(a.created_at) period,COUNT(*)::int value FROM audit_logs a LEFT JOIN roles r ON r.id=a.role_id_at_action WHERE ${where} GROUP BY 1 ORDER BY 1`,values),
    executor.query(`SELECT a.module label,COUNT(*)::int value FROM audit_logs a LEFT JOIN roles r ON r.id=a.role_id_at_action WHERE ${where} GROUP BY a.module ORDER BY value DESC LIMIT 12`,values),
    executor.query(`SELECT COALESCE(r.role_name,'System') label,COUNT(*)::int value FROM audit_logs a LEFT JOIN roles r ON r.id=a.role_id_at_action WHERE ${where} GROUP BY 1 ORDER BY value DESC`,values),
    executor.query(`SELECT a.action label,COUNT(*)::int value FROM audit_logs a LEFT JOIN roles r ON r.id=a.role_id_at_action WHERE ${where} GROUP BY a.action ORDER BY value DESC LIMIT 12`,values),
    executor.query(`SELECT COUNT(*) total FROM audit_logs a LEFT JOIN roles r ON r.id=a.role_id_at_action WHERE ${where}`,values),
    executor.query(`SELECT a.created_at timestamp,COALESCE(u.full_name,u.username,'System') "user",COALESCE(r.role_name,'System') role,a.module,a.action,a.metadata->>'entity_type' entity_type,COALESCE(a.metadata->>'entity_reference',a.metadata->>'public_reference') entity_reference,COALESCE(a.metadata->>'before',a.metadata->>'previous_value') previous_summary,COALESCE(a.metadata->>'after',a.metadata->>'new_value') new_summary,a.metadata->>'ip_address' ip_address,a.metadata->>'session_reference' session_reference FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id LEFT JOIN roles r ON r.id=a.role_id_at_action WHERE ${where} ORDER BY a.created_at DESC LIMIT $3 OFFSET $4`,values),
    executor.query(`SELECT ARRAY(SELECT role_key FROM roles ORDER BY role_key) roles,ARRAY(SELECT DISTINCT module FROM audit_logs ORDER BY 1) modules,ARRAY(SELECT DISTINCT action FROM audit_logs ORDER BY 1) actions`)
  ]);
  return {kpis:summary.rows[0],charts:[{title:"Audit Events Over Time",type:"line",data:time.rows},{title:"Events by Module",type:"bar",data:modules.rows},{title:"Events by Role",type:"pie",data:roles.rows},{title:"Events by Action Type",type:"bar",data:actions.rows}],tables:[table("audit","Audit Events",Object.keys(rows.rows[0]||{}),rows.rows,filters,count.rows[0].total)],options:options.rows[0]};
}

async function supervisor(filters, auth, executor) {
  const v=[filters.dateFrom,filters.dateTo,auth.warehouseId||null,filters.pageSize,(filters.page-1)*filters.pageSize,`%${filters.search}%`];
  const scope=`($3::int IS NULL OR c.warehouse_id=$3)`;
  const [summary,received,activity,zones,statuses,count,rows,util]=await Promise.all([
    executor.query(`SELECT COUNT(*) FILTER(WHERE c.placement_status IN ('Placed','Relocated'))::int cargo_in_storage,(SELECT COUNT(*) FROM bins b JOIN levels l ON l.id=b.level_id JOIN racks r ON r.id=l.rack_id JOIN zones z ON z.id=r.zone_id WHERE b.active=TRUE AND b.status IN ('Occupied','Full') AND ($3::int IS NULL OR z.warehouse_id=$3))::int occupied_bins,(SELECT COUNT(*) FROM bins b JOIN levels l ON l.id=b.level_id JOIN racks r ON r.id=l.rack_id JOIN zones z ON z.id=r.zone_id WHERE b.active=TRUE AND b.status='Available' AND ($3::int IS NULL OR z.warehouse_id=$3))::int available_bins,COUNT(*) FILTER(WHERE c.placement_status='Unplaced')::int awaiting_placement,COUNT(*) FILTER(WHERE c.release_readiness_status='READY_FOR_RELEASE')::int awaiting_release FROM cargo c WHERE c.is_deleted=FALSE AND ${scope} AND ${period("c.created_at")}`,[v[0],v[1],v[2]]),
    executor.query(`SELECT DATE(c.created_at) period,COUNT(*)::int value FROM cargo c WHERE c.is_deleted=FALSE AND ${scope} AND ${period("c.created_at")} GROUP BY 1 ORDER BY 1`,v.slice(0,3)),
    executor.query(`SELECT DATE(cm.created_at) period,COUNT(*)::int value FROM cargo_movements cm JOIN cargo c ON c.id=cm.cargo_id WHERE ${scope} AND ${period("cm.created_at")} GROUP BY 1 ORDER BY 1`,v.slice(0,3)),
    executor.query(`SELECT COALESCE(z.name,'Unplaced') label,COUNT(*)::int value FROM cargo c LEFT JOIN bins b ON b.id=c.current_bin_id LEFT JOIN levels l ON l.id=b.level_id LEFT JOIN racks r ON r.id=l.rack_id LEFT JOIN zones z ON z.id=r.zone_id WHERE c.is_deleted=FALSE AND ${scope} AND ${period("c.created_at")} GROUP BY 1 ORDER BY value DESC`,v.slice(0,3)),
    executor.query(`SELECT c.placement_status label,COUNT(*)::int value FROM cargo c WHERE c.is_deleted=FALSE AND ${scope} AND ${period("c.created_at")} GROUP BY c.placement_status ORDER BY label`,v.slice(0,3)),
    executor.query(`SELECT COUNT(*) total FROM cargo c WHERE c.is_deleted=FALSE AND $1::date IS NOT DISTINCT FROM $1::date AND $2::date IS NOT DISTINCT FROM $2::date AND $4::int>0 AND $5::int>=0 AND ${scope} AND ($6='%%' OR c.cargo_id ILIKE $6 OR c.reference_number ILIKE $6)`,v),
    executor.query(`SELECT c.cargo_id cargo_reference,c.registration_status,c.placement_status,c.customs_status,c.release_readiness_status,c.location,c.created_at registration_date FROM cargo c WHERE c.is_deleted=FALSE AND ${scope} AND ${period("c.created_at")} AND ($6='%%' OR c.cargo_id ILIKE $6 OR c.reference_number ILIKE $6) ORDER BY c.created_at DESC LIMIT $4 OFFSET $5`,v),
    executor.query(`SELECT z.name zone,COUNT(b.id)::int total_bins,COUNT(b.id) FILTER(WHERE b.status IN ('Occupied','Full'))::int occupied_bins FROM zones z LEFT JOIN racks r ON r.zone_id=z.id LEFT JOIN levels l ON l.rack_id=r.id LEFT JOIN bins b ON b.level_id=l.id AND b.active=TRUE WHERE ($1::int IS NULL OR z.warehouse_id=$1) GROUP BY z.id,z.name ORDER BY z.name`,[auth.warehouseId||null])
  ]);
  return {kpis:summary.rows[0],charts:[{title:"Cargo Received Over Time",type:"line",data:received.rows},{title:"Placement Activity",type:"line",data:activity.rows},{title:"Cargo by Zone",type:"pie",data:zones.rows},{title:"Cargo by Status",type:"bar",data:statuses.rows},{title:"Storage Utilization",type:"bar",data:util.rows.map(x=>({label:x.zone,value:x.total_bins?Math.round(100*Number(x.occupied_bins)/Number(x.total_bins)):0}))}],tables:[table("cargo","Operational Cargo",Object.keys(rows.rows[0]||{}),rows.rows,filters,count.rows[0].total),table("utilization","Warehouse Utilization",Object.keys(util.rows[0]||{}),util.rows,filters,util.rowCount)]};
}

async function admin(filters, executor){const v=paging(filters);const [summary,activity,count,rows]=await Promise.all([executor.query(`SELECT COUNT(*) FILTER(WHERE status='active')::int active_users,COUNT(*) FILTER(WHERE status IN ('inactive','suspended'))::int inactive_users,(SELECT COUNT(*) FROM user_sessions WHERE session_status='active')::int active_sessions,(SELECT COUNT(*) FROM audit_logs WHERE ${period("created_at")})::int audit_events,(SELECT COUNT(*) FROM audit_logs WHERE (module ILIKE '%configuration%' OR action ILIKE '%CONFIG%') AND ${period("created_at")})::int configuration_changes FROM users`,v.slice(0,2)),executor.query(`SELECT COALESCE(r.role_name,'System') label,COUNT(a.id)::int value FROM audit_logs a LEFT JOIN roles r ON r.id=a.role_id_at_action WHERE ${period("a.created_at")} GROUP BY 1 ORDER BY value DESC`,v.slice(0,2)),executor.query(`SELECT COUNT(*) total FROM audit_logs a WHERE $3::int>0 AND $4::int>=0 AND ${period("a.created_at")} AND ($5='%%' OR a.action ILIKE $5 OR a.module ILIKE $5 OR a.description ILIKE $5)`,v),executor.query(`SELECT a.created_at timestamp,COALESCE(u.full_name,u.username,'System') "user",a.module,a.action,a.description FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id WHERE ${period("a.created_at")} AND ($5='%%' OR a.action ILIKE $5 OR a.module ILIKE $5 OR a.description ILIKE $5) ORDER BY a.created_at DESC LIMIT $3 OFFSET $4`,v)]);return{kpis:summary.rows[0],charts:[{title:"Activity by Role",type:"bar",data:activity.rows}],tables:[table("activity","System Activity",Object.keys(rows.rows[0]||{}),rows.rows,filters,count.rows[0].total)]};}

async function customs(filters, executor){const v=paging(filters);const [summary,time,status,count,rows]=await Promise.all([executor.query(`SELECT COUNT(*) FILTER(WHERE status IN ('Pending Inspection','Inspection In Progress','Documents Required','On Hold'))::int awaiting_customs,COUNT(*) FILTER(WHERE status='Cleared')::int cleared,COUNT(*) FILTER(WHERE status='Rejected')::int rejected,ROUND(AVG(EXTRACT(EPOCH FROM (inspection_completed_at-created_at))/3600) FILTER(WHERE inspection_completed_at IS NOT NULL),2) average_clearance_hours,COUNT(*) FILTER(WHERE inspection_completed_at IS NOT NULL AND ${period("inspection_completed_at")})::int clearance_activity FROM customs_records`,v.slice(0,2)),executor.query(`SELECT DATE(ch.changed_at) period,COUNT(*)::int value FROM customs_status_history ch WHERE ${period("ch.changed_at")} GROUP BY 1 ORDER BY 1`,v.slice(0,2)),executor.query(`SELECT status label,COUNT(*)::int value FROM customs_records GROUP BY status ORDER BY label`),executor.query(`SELECT COUNT(*) total FROM customs_records cr JOIN cargo c ON c.id=cr.cargo_id WHERE $3::int>0 AND $4::int>=0 AND ${period("cr.created_at")} AND ($5='%%' OR c.cargo_id ILIKE $5 OR cr.public_reference ILIKE $5)`,v),executor.query(`SELECT c.cargo_id cargo_reference,cr.status customs_status,cr.status decision,COALESCE(u.full_name,u.username) customs_officer,cr.created_at submission_date,cr.inspection_completed_at decision_date,CASE WHEN cr.inspection_completed_at IS NOT NULL THEN ROUND(EXTRACT(EPOCH FROM (cr.inspection_completed_at-cr.created_at))/3600,2) END processing_hours FROM customs_records cr JOIN cargo c ON c.id=cr.cargo_id LEFT JOIN users u ON u.id=cr.officer_id WHERE ${period("cr.created_at")} AND ($5='%%' OR c.cargo_id ILIKE $5 OR cr.public_reference ILIKE $5) ORDER BY cr.created_at DESC LIMIT $3 OFFSET $4`,v)]);return{kpis:summary.rows[0],charts:[{title:"Customs Decisions Over Time",type:"line",data:time.rows},{title:"Customs Status Distribution",type:"pie",data:status.rows}],tables:[table("customs","Customs Activity",Object.keys(rows.rows[0]||{}),rows.rows,filters,count.rows[0].total)]};}

async function gate(filters, executor){const v=paging(filters);const [summary,activity,readiness,blockers,count,rows]=await Promise.all([executor.query(`SELECT COUNT(*) FILTER(WHERE release_readiness_status='READY_FOR_RELEASE' AND gate_out_status='Not Released')::int ready_for_gate_out,COUNT(*) FILTER(WHERE release_readiness_status<>'READY_FOR_RELEASE' AND gate_out_status='Not Released')::int blocked_releases,(SELECT COUNT(*) FROM gate_out_records WHERE released_at::date=CURRENT_DATE)::int gate_out_today,(SELECT COUNT(*) FROM gate_out_records WHERE ${period("released_at")})::int gate_out_period,COUNT(*) FILTER(WHERE management_release_status='PENDING')::int management_pending FROM cargo WHERE is_deleted=FALSE`,v.slice(0,2)),executor.query(`SELECT DATE(released_at) period,COUNT(*)::int value FROM gate_out_records WHERE ${period("released_at")} GROUP BY 1 ORDER BY 1`,v.slice(0,2)),executor.query(`SELECT release_readiness_status label,COUNT(*)::int value FROM cargo WHERE is_deleted=FALSE AND gate_out_status='Not Released' GROUP BY release_readiness_status ORDER BY label`),executor.query(`SELECT blocker->>'code' label,COUNT(*)::int value FROM cargo c CROSS JOIN LATERAL jsonb_array_elements(COALESCE(c.release_readiness_blockers,'[]')) blocker WHERE c.is_deleted=FALSE AND c.gate_out_status='Not Released' GROUP BY 1 ORDER BY value DESC`),executor.query(`SELECT COUNT(*) total FROM cargo c WHERE c.is_deleted=FALSE AND $1::date IS NOT DISTINCT FROM $1::date AND $2::date IS NOT DISTINCT FROM $2::date AND $3::int>0 AND $4::int>=0 AND ($5='%%' OR c.cargo_id ILIKE $5 OR c.reference_number ILIKE $5)`,v),executor.query(`SELECT c.cargo_id cargo_reference,c.release_readiness_status gate_readiness,COALESCE(c.release_readiness_blockers->0->>'message','—') block_reason,c.management_release_status management_status,c.customs_status,c.financial_status payment_status,c.placement_status,c.registration_status,g.released_at gate_out_timestamp FROM cargo c LEFT JOIN gate_out_records g ON g.cargo_id=c.id WHERE c.is_deleted=FALSE AND ${period("c.created_at")} AND ($5='%%' OR c.cargo_id ILIKE $5 OR c.reference_number ILIKE $5) ORDER BY COALESCE(g.released_at,c.created_at) DESC LIMIT $3 OFFSET $4`,v)]);return{kpis:summary.rows[0],charts:[{title:"Gate-Out Activity",type:"line",data:activity.rows},{title:"Release Readiness Distribution",type:"pie",data:readiness.rows},{title:"Gate Block Reasons",type:"bar",data:blockers.rows}],tables:[table("gate","Gate Readiness",Object.keys(rows.rows[0]||{}),rows.rows,filters,count.rows[0].total)]};}

async function staff(filters, auth, executor){const v=[filters.dateFrom,filters.dateTo,auth.userId,filters.pageSize,(filters.page-1)*filters.pageSize];const [summary,activity,count,rows]=await Promise.all([executor.query(`SELECT COUNT(*) FILTER(WHERE c.received_by_user_id=$3 OR c.created_by=$3)::int cargo_received,(SELECT COUNT(*) FROM cargo_movements WHERE moved_by_user_id=$3 AND action ILIKE '%PLAC%')::int cargo_placed,(SELECT COUNT(*) FROM cargo_movements WHERE moved_by_user_id=$3 AND (movement_type ILIKE '%RELOCAT%' OR action ILIKE '%RELOCAT%'))::int cargo_relocated,(SELECT COUNT(*) FROM cargo_movements WHERE moved_by_user_id=$3 AND ${period("created_at")})::int tasks_completed FROM cargo c WHERE ${period("c.created_at")}`,[v[0],v[1],v[2]]),executor.query(`SELECT DATE(created_at) period,COUNT(*)::int value FROM cargo_movements WHERE moved_by_user_id=$3 AND ${period("created_at")} GROUP BY 1 ORDER BY 1`,v.slice(0,3)),executor.query(`SELECT COUNT(*) total FROM cargo_movements WHERE moved_by_user_id=$3 AND ${period("created_at")}`,v.slice(0,3)),executor.query(`SELECT cm.created_at timestamp,c.cargo_id cargo_reference,cm.action,cm.from_location,cm.to_location FROM cargo_movements cm JOIN cargo c ON c.id=cm.cargo_id WHERE cm.moved_by_user_id=$3 AND ${period("cm.created_at")} ORDER BY cm.created_at DESC LIMIT $4 OFFSET $5`,v)]);return{kpis:summary.rows[0],charts:[{title:"My Operational Activity",type:"line",data:activity.rows}],tables:[table("activity","My Completed Work",Object.keys(rows.rows[0]||{}),rows.rows,filters,count.rows[0].total)]};}

async function getRoleReport(scope, query, auth, executor=db){const filters={...parseFilters(query),role:query.role||null,module:query.module||null,action:query.action||null,userId:query.userId||null};let data;if(scope==='finance')data=await finance(filters,executor);else if(scope==='auditor')data=await auditor(filters,executor);else if(scope==='supervisor')data=await supervisor(filters,auth,executor);else if(scope==='admin')data=await admin(filters,executor);else if(scope==='customs')data=await customs(filters,executor);else if(scope==='gate')data=await gate(filters,executor);else if(scope==='warehouse')data=await staff(filters,auth,executor);else throw Object.assign(new Error('Unknown report scope.'),{statusCode:404});return{scope,filters,...data};}

module.exports={getRoleReport};
