const { getRoleReport } = require("../services/roleReportService");
const { normalizeRole } = require("../middleware/authMiddleware");

const allowed = Object.freeze({ finance:"finance-officer",auditor:"auditor",supervisor:"warehouse-supervisor",admin:"system-admin",customs:"customs-officer",gate:"gate-officer",warehouse:"warehouse-staff" });
function assertScope(req){const scope=String(req.params.scope||"").toLowerCase();if(!allowed[scope])throw Object.assign(new Error("Unknown report scope."),{statusCode:404});if(normalizeRole(req.auth?.role)!==allowed[scope])throw Object.assign(new Error("This report is restricted to its authorized portal role."),{statusCode:403});return scope;}
const get=async(req,res,next)=>{try{const scope=assertScope(req);res.json({success:true,data:await getRoleReport(scope,req.query,req.auth)});}catch(error){next(error)}};
const xml=(v)=>String(v??"").replace(/[<>&'\"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&apos;",'"':"&quot;"})[c]);
const safeName=(v)=>String(v).replace(/[\\/?*\[\]:]/g," ").slice(0,31);
const excel=(scope,data)=>{const sheets=[{title:"Summary",rows:[["Metric","Value"],...Object.entries(data.kpis||{})]}];for(const t of data.tables||[])sheets.push({title:t.title,rows:[t.columns,...t.rows.map(r=>t.columns.map(c=>r[c]))]});for(const c of data.charts||[])sheets.push({title:c.title,rows:[["Label","Value"],...(c.data||[]).map(r=>[r.label??r.period,r.value])]});return `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">${sheets.map(s=>`<Worksheet ss:Name="${xml(safeName(s.title))}"><Table>${s.rows.map((row,ri)=>`<Row>${row.map(v=>`<Cell><Data ss:Type="${ri&&v!==''&&v!==null&&!Number.isNaN(Number(v))?'Number':'String'}">${xml(v)}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet>`).join('')}</Workbook>`;};
const pdf=(scope,data)=>{const lines=[`Fumba Port WMS - ${scope.toUpperCase()} Reports`,`Generated: ${new Date().toISOString()}`,...Object.entries(data.kpis||{}).map(([k,v])=>`${k.replaceAll('_',' ')}: ${v??'N/A'}`),`Filters: ${JSON.stringify(data.filters)}`].slice(0,28);const stream=`BT /F1 10 Tf 42 780 Td ${lines.map((x,i)=>`${i?'0 -20 Td ':''}(${String(x).replace(/[()\\]/g,'\\$&').slice(0,105)}) Tj`).join(' ')} ET`;const objects=[`1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj`,`2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj`,`3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>endobj`,`4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj`,`5 0 obj<</Length ${Buffer.byteLength(stream)}>>stream\n${stream}\nendstream endobj`];let out='%PDF-1.4\n',offsets=[0];for(const o of objects){offsets.push(Buffer.byteLength(out));out+=o+'\n'}const x=Buffer.byteLength(out);out+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer<</Size 6/Root 1 0 R>>\nstartxref\n${x}\n%%EOF`;return Buffer.from(out)};
const exportReport=async(req,res,next)=>{try{const scope=assertScope(req);const data=await getRoleReport(scope,{...req.query,page:1,pageSize:100},req.auth);const format=String(req.params.format).toLowerCase();if(format==='excel'){res.set({'Content-Type':'application/vnd.ms-excel','Content-Disposition':`attachment; filename=${scope}-report.xls`}).send(excel(scope,data));return}if(format==='pdf'){res.set({'Content-Type':'application/pdf','Content-Disposition':`attachment; filename=${scope}-report.pdf`}).send(pdf(scope,data));return}res.status(400).json({success:false,message:'Unsupported export format.'});}catch(error){next(error)}};
module.exports={get,exportReport,allowed,assertScope};
