const route = (methods, pattern, permission) => Object.freeze({ methods, pattern, permission });

const AUTHORIZATION_ROUTES = Object.freeze([
  route(["GET"], /^\/cargo-registration-form$/, "cargo.registration_metadata.view"),
  route(["GET"], /^\/cargo-registration-form\/available$/, "system.cargo_registration_form.view"),
  route(["POST", "PUT"], /^\/cargo-registration-form(?:\/validate|\/reset)?$/, "system.cargo_registration_form.manage"),
  route(["GET"], /^\/cargo(?:\/.*)?$/, "cargo.view"), route(["POST"], /^\/cargo$/, "cargo.register"),
  route(["PUT"], /^\/cargo\/[^/]+$/, "cargo.edit"), route(["DELETE"], /^\/cargo\/[^/]+$/, "system.configuration.manage"),
  route(["POST"], /^\/cargo\/[^/]+\/documents$/, "cargo.documents.manage"),
  route(["POST"], /^\/cargo\/[^/]+\/print-barcode$/, "cargo.barcode.print"),
  route(["POST"], /^\/cargo\/[^/]+\/resubmit$/, "cargo.resubmit"),
  route(["PATCH"], /^\/cargo\/[^/]+\/status$/, "cargo.approve"),
  route(["GET"], /^\/(?:zones|racks|levels|bins)(?:\/.*)?$/, "warehouse.hierarchy.view"),
  route(["POST"], /^\/bins\/[^/]+\/print-barcode$/, "warehouse.labels.print"),
  route(["POST", "PUT", "PATCH", "DELETE"], /^\/(?:zones|racks|levels|bins)(?:\/.*)?$/, "warehouse.hierarchy.manage"),
  route(["GET"], /^\/warehouses$/, "warehouse.configuration.view"),
  route(["GET"], /^\/warehouses\/(?:assignments|assignment-history)$/, "warehouse.configuration.view"),
  route(["POST", "PUT", "PATCH", "DELETE"], /^\/warehouses(?:\/.*)?$/, "warehouse.configuration.manage"),
  route(["GET"], /^\/capacity-configurations$/, "warehouse.configuration.view"),
  route(["PUT"], /^\/capacity-configurations\/.*$/, "warehouse.configuration.manage"),
  route(["GET"], /^\/shifts(?:\/.*)?$/, "warehouse.shifts.view"),
  route(["POST", "PUT", "PATCH", "DELETE"], /^\/shifts(?:\/.*)?$/, "warehouse.shifts.manage"),
  route(["GET"], /^\/bin-rules(?:\/.*)?$/, "bin_rules.view"), route(["POST", "PUT", "DELETE"], /^\/bin-rules(?:\/.*)?$/, "bin_rules.manage"),
  route(["GET"], /^\/placement\/logs$/, "placement.logs.view"), route(["GET"], /^\/placement\/failures$/, "placement.failures.view"),
  route(["GET"], /^\/placement\/activity(?:\/summary)?$/, "placement.activity.view"),
  route(["GET"], /^\/placement\/settings$/, "placement.settings.view"), route(["PUT"], /^\/placement\/settings$/, "placement.settings.manage"),
  route(["POST"], /^\/placement\/validate$/, "placement.validate"), route(["POST"], /^\/placement\/confirm$/, "placement.confirm"),
  route(["POST"], /^\/placement\/request-override$/, "placement.override.request"),
  route(["GET"], /^\/supervisor\/(?:dashboard|my\/review-history|review-configuration)$/, "supervisor.dashboard.view"),
  route(["GET"], /^\/supervisor\/approvals(?:\/.*)?$/, "supervisor.approvals.view"),
  route(["POST"], /^\/supervisor\/approvals\/[^/]+\/.*$/, "cargo.approve"),
  route(["POST"], /^\/supervisor\/cargo\/[^/]+\/management-release\/(?:normal|resubmit)$/, "management_release.request"),
  route(["GET"], /^\/supervisor\/(?:staff-activity|placement-monitoring|placement-summary)$/, "supervisor.monitoring.view"),
  route(["POST"], /^\/dispatch\/request-authorization$/, "dispatch.requests.create"), route(["GET"], /^\/dispatch\/authorization-requests$/, "dispatch.requests.view"),
  route(["POST"], /^\/dispatch\/authorization-requests\/[^/]+\/(?:approve|reject)$/, "dispatch.requests.decide"),
  route(["GET"], /^\/finance\/dashboard$/, "finance.dashboard.view"), route(["GET"], /^\/finance\/cargo-charges$/, "finance.charges.view"),
  route(["GET"], /^\/finance\/tariffs$/, "finance.tariffs.view"), route(["POST"], /^\/finance\/tariffs$/, "finance.tariffs.create"),
  route(["PUT"], /^\/finance\/tariffs\/[^/]+$/, "finance.tariffs.update"), route(["POST"], /^\/finance\/tariffs\/[^/]+\/(?:activate|deactivate)$/, "finance.tariffs.activate"),
  route(["GET"], /^\/finance\/invoices(?:\/.*)?$/, "finance.invoices.view"), route(["POST"], /^\/finance\/invoices\/draft$/, "finance.invoices.create"),
  route(["POST"], /^\/finance\/invoices\/[^/]+\/issue$/, "finance.invoices.issue"), route(["POST"], /^\/finance\/invoices\/[^/]+\/cancel$/, "finance.invoices.cancel"),
  route(["GET", "POST"], /^\/finance\/payments$/, "finance.payments.record"), route(["POST"], /^\/finance\/payments\/[^/]+\/confirm$/, "finance.payments.confirm"), route(["GET"], /^\/finance\/reports$/, "finance.reports.view"),
  route(["GET"], /^\/customs\/dashboard$/, "customs.dashboard.view"), route(["GET"], /^\/customs\/(?:queue|records|cleared|holds)$/, "customs.cargo.view"),
  route(["GET"], /^\/customs\/cargo\/[^/]+$/, "customs.cargo.view"), route(["GET"], /^\/customs\/cargo\/[^/]+\/history$/, "customs.history.view"),
  route(["POST"], /^\/customs\/cargo\/[^/]+\/start$/, "customs.inspections.create"), route(["POST"], /^\/customs\/cargo\/[^/]+\/status$/, "customs.clearance.update"),
  route(["GET"], /^\/gate\/dashboard$/, "gate.dashboard.view"), route(["GET"], /^\/gate\/release-queue$/, "gate.release_queue.view"),
  route(["GET"], /^\/gate\/records$/, "gate.history.view"), route(["GET"], /^\/gate\/cargo\/[^/]+\/eligibility$/, "gate.release.validate"),
  route(["POST"], /^\/gate\/cargo\/[^/]+\/gate-out$/, "gate.gate_out.confirm"), route(["GET"], /^\/gate\/emergency-requests$/, "gate.history.view"),
  route(["POST"], /^\/gate\/emergency-requests$/, "gate.emergency_release.request"), route(["POST"], /^\/gate\/emergency-requests\/[^/]+\/(?:approve|reject)$/, "gate.emergency_release.approve"),
  route(["GET"], /^\/management\/dashboard$/, "management.dashboard.view"), route(["GET"], /^\/management\/reports$/, "management.reports.view"),
  route(["POST"], /^\/finance\/tariffs\/[^/]+\/submit$/, "finance.tariffs.submit"),
  route(["GET"], /^\/management\/tariff-approvals$/, "management.tariffs.view"), route(["POST"], /^\/management\/tariff-approvals\/[^/]+\/(?:approve|reject)$/, "management.tariffs.decide"),
  route(["POST"], /^\/payments\/invoices\/[^/]+\/initiate$/, "finance.payments.initiate"), route(["POST"], /^\/payments\/cargo\/[^/]+\/automatic-billing$/, "finance.payments.initiate"),
  route(["GET"], /^\/release-readiness\/cargo-to-release$/, "staff.release_queue.view"),
  route(["GET"], /^\/management\/release-requests(?:\/[^/]+)?$/, "management_release.view"),
  route(["POST"], /^\/management\/release-requests\/[^/]+\/(?:approve|reject)$/, "management_release.decide"),
  route(["GET"], /^\/users(?:\/.*)?$/, "system.users.view"), route(["POST", "PUT", "PATCH", "DELETE"], /^\/users(?:\/.*)?$/, "system.users.manage"),
  route(["GET"], /^\/roles$/, "system.roles.view"), route(["GET"], /^\/audit-logs(?:\/export)?$/, "system.audit.view"), route(["POST"], /^\/audit-logs\/archive$/, "system.configuration.manage"), route(["GET"], /^\/user-sessions$/, "system.sessions.view"),
  route(["GET", "PUT"], /^\/notifications\/policies(?:\/.*)?$/, "system.notifications.configure"), route(["GET"], /^\/notifications(?:\/.*)?$/, "notifications.view"), route(["PATCH", "DELETE"], /^\/notifications(?:\/.*)?$/, "notifications.manage"),
  route(["POST"], /^\/notifications\/system-announcement$/, "system.notifications.announce"),
  route(["GET"], /^\/admin\/roles$/, "system.roles.view"), route(["GET"], /^\/admin\/permissions$/, "system.permissions.view"),
  route(["GET"], /^\/admin\/roles\/[^/]+\/permissions$/, "system.permissions.view"), route(["PUT"], /^\/admin\/roles\/[^/]+\/permissions$/, "system.permissions.manage"),
  route(["GET", "PUT"], /^\/admin\/notification-escalation$/, "system.notifications.configure"),
  route(["GET"], /^\/admin\/readiness$/, "system.configuration.view"), route(["POST"], /^\/admin\/configuration\/validate$/, "system.configuration.manage"),
  route(["GET"], /^\/admin\/configuration\/backup$/, "system.configuration.view"), route(["POST"], /^\/admin\/configuration\/backup\/validate$/, "system.configuration.manage"),
  route(["POST"], /^\/admin\/configuration\/restore$/, "system.configuration.manage")
]);

const getRoutePermission = (method, path) => AUTHORIZATION_ROUTES.find((entry) => entry.methods.includes(method) && entry.pattern.test(path))?.permission || null;
const referencedPermissions = Object.freeze([...new Set(AUTHORIZATION_ROUTES.map((entry) => entry.permission))]);

module.exports = { AUTHORIZATION_ROUTES, getRoutePermission, referencedPermissions };
