FROM node:20.19-alpine3.21

ENV NODE_ENV=production
WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev --ignore-scripts && npm cache clean --force

COPY --chown=node:node . .
USER node

EXPOSE 5000
CMD ["node", "server.js"]
