const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {eligibilityEvaluatorRegistry,evaluateRequirement}=require('../services/eligibilityEvaluatorRegistry');
const migration=fs.readFileSync(path.join(__dirname,'../database/migrations/20260813_dispatch_gate_policy_authority.sql'),'utf8');
test('migration 027 defines revisioned policies and trusted requirements',()=>{for(const key of ['dispatch_request','normal_gate_release','emergency_gate_release'])assert.match(migration,new RegExp(`'${key}'`));assert.match(migration,/idx_dispatch_one_pending/);assert.match(migration,/consumed_at/)});
test('normal Gate policy uses the five existing authoritative requirements',()=>{for(const key of ['registration_state','customs_clearance','financial_clearance','dispatch_approval','release_state'])assert.match(migration,new RegExp(`'normal_gate_release',1,'${key}'`))});
test('trusted evaluators use stable state keys and fail closed',()=>{assert.equal(evaluateRequirement('normal_gate_release','customs_clearance',{customs_state_key:'cleared'},{required_state:'cleared'}).passed,true);assert.equal(evaluateRequirement('normal_gate_release','financial_clearance',{outstanding_cents:1n,outstanding_amount:'0.01'},{}).passed,false);assert.throws(()=>evaluateRequirement('normal_gate_release','unknown',{},{}),/invalid/i)});
test('emergency policy bypasses normal blockers but never authorization or release state',()=>{assert.match(migration,/'emergency_gate_release',1,'emergency_authorization'/);assert.match(migration,/'emergency_gate_release',1,'release_state'/);assert.doesNotMatch(migration,/'emergency_gate_release',1,'financial_clearance'/)});
test('Gate release integrates Phase 5 dispatch and Phase 6 charge stop transactionally',()=>{const source=fs.readFileSync(path.join(__dirname,'../controllers/gateController.js'),'utf8');assert.match(source,/executeTransition\(\{workflowKey:'cargo_placement',transitionKey:'finalize_gate_release'/);assert.match(source,/charge_end_at = \$1/);assert.doesNotMatch(source,/SET placement_status = 'Dispatched'/)});
test('eligibility registry contains only code-owned target-compatible evaluators',()=>{assert.deepEqual(Object.keys(eligibilityEvaluatorRegistry).sort(),['customs_clearance','dispatch_approval','emergency_authorization','financial_clearance','placement_state','registration_state','release_state'].sort())});
