const test=require("node:test");
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const {evaluateRequirement}=require("../services/eligibilityEvaluatorRegistry");
const root=path.join(__dirname,"..");
const read=file=>fs.readFileSync(path.join(root,file),"utf8");
const evaluate=(release_type,management_release_status)=>evaluateRequirement("normal_gate_release","management_release_authorization",{cargo:{release_type,management_release_status}},{});
const gate=read("controllers/gateController.js");
const finance=read("services/financeService.js");
const management=read("services/managementReleaseService.js");
const placement=read("services/placementService.js");
const migration=read("database/migrations/20260816_management_release_gate_authority.sql");

test("1 NORMAL + NOT_REQUIRED uses the normal Gate path",()=>assert.equal(evaluate("NORMAL","NOT_REQUIRED").passed,true));
test("2 MANAGEMENT + PENDING is Gate blocked",()=>assert.deepEqual(evaluate("MANAGEMENT","PENDING"),{passed:false,reason_code:"MANAGEMENT_RELEASE_PENDING",message:"Management Release approval is pending. Management approval is required before Gate-Out."}));
test("3 MANAGEMENT + REJECTED is Gate blocked",()=>assert.equal(evaluate("MANAGEMENT","REJECTED").reason_code,"MANAGEMENT_RELEASE_REJECTED"));
test("4 only MANAGEMENT + APPROVED satisfies Management authorization",()=>assert.equal(evaluate("MANAGEMENT","APPROVED").passed,true));
test("5 approval does not remove Customs from normal Gate policy",()=>assert.match(migration,/normal_gate_release',2,'customs_clearance/));
test("6 approval does not remove dispatch from normal Gate policy",()=>assert.match(migration,/normal_gate_release',2,'dispatch_approval/));
test("7 pending Management cargo remains placement independent",()=>assert.doesNotMatch(placement,/management_release/i));
test("8 rejected Management cargo remains placement independent",()=>assert.doesNotMatch(management,/placement_status\s*=/i));
test("9 paid pending cargo remains blocked because evaluator ignores payment",()=>assert.equal(evaluate("MANAGEMENT","PENDING").passed,false));
test("10 zero-balance pending cargo remains blocked because evaluator ignores balance",()=>assert.equal(evaluate("MANAGEMENT","PENDING").reason_code,"MANAGEMENT_RELEASE_PENDING"));
test("11 approval records historical and waived amounts",()=>{assert.match(management,/historical_accrued_amount/);assert.match(management,/management_release_waived_amount/)});
test("12 approval cancels unpaid invoices with explicit reason",()=>assert.match(management,/cancellation_reason='Management Release Approved'[\s\S]*amount_paid=0/));
test("13 paid history is preserved and flagged for review",()=>{assert.match(management,/financeReview=Number\(invoiceTotals\.paid\)>0/);assert.match(management,/management_release_finance_review_required/)});
test("14 approved cargo cannot receive a payable invoice",()=>assert.equal((finance.match(/MANAGEMENT_RELEASE_NO_CHARGES/g)||[]).length,2));
test("15 rejected to Normal returns trusted Normal state without timestamp resets",()=>{assert.match(management,/release_type='NORMAL',management_release_status='NOT_REQUIRED'/);assert.doesNotMatch(management,/charge_start_at\s*=/)});
test("16 rejected resubmission returns to Pending and preserves history",()=>{assert.match(management,/\[STATUS\.NOT_REQUIRED, STATUS\.REJECTED\]/);assert.match(management,/INSERT INTO management_release_requests/)});
test("17 direct normal Gate API maps and returns Management block",()=>{assert.match(gate,/management_release_authorization:'management_release'/);assert.match(gate,/managementBlock\?\.reason_code/)});
test("18 direct emergency Gate API cannot bypass Management",()=>assert.match(migration,/emergency_gate_release',2,'management_release_authorization/));
test("19 Management approval and Gate serialize on the cargo row",()=>{assert.match(management,/FOR UPDATE OF mrr,c/);assert.match(gate,/findCargoByPublicReference\(client,[^\n]+lock: true/)});
test("20 Management approval and invoice generation serialize and revalidate",()=>{assert.match(management,/SELECT id FROM invoices[\s\S]*FOR UPDATE/);assert.match(finance,/management_release_status FROM cargo WHERE id=\$1 FOR UPDATE/)});
test("invalid mixed release state fails closed",()=>assert.equal(evaluate("NORMAL","PENDING").reason_code,"MANAGEMENT_RELEASE_STATE_INVALID"));
test("emergency evaluator also blocks pending Management cargo",()=>assert.equal(evaluateRequirement("emergency_gate_release","management_release_authorization",{cargo:{release_type:"MANAGEMENT",management_release_status:"PENDING"}},{}).passed,false));
