import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Boxes, CircleDollarSign, Download, FileSpreadsheet, Search, X } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ErrorState, PaginationControls } from "./OperationalUi";
import { exportManagementReport, getManagementReports } from "@/services/api";

const colors=["#1976d2","#32b45f","#f0a009","#d10925","#18558c","#7c3aed"];
const money = value => `TZS ${Number(value || 0).toLocaleString("en-TZ", {maximumFractionDigits:2})}`;
const initial={dateFrom:"",dateTo:"",cargoStatus:"",customsStatus:"",paymentStatus:"",warehouseId:"",zoneId:"",cargoType:"",search:"",page:1,pageSize:20,sortBy:"date",sortOrder:"desc"};
const Card=({title,children,className=""})=><section className={`overflow-hidden rounded-md border bg-card ${className}`}><h2 className="border-b bg-slate-200/80 px-4 py-3 text-sm font-semibold text-slate-800">{title}</h2>{children}</section>;
const ChartCard=({title,children,empty})=><Card title={title}><div className="h-72 p-4">{empty?<div className="grid h-full place-items-center text-sm text-muted-foreground">No data is available for this period.</div>:children}</div></Card>;
const Kpi=({label,value,icon:Icon,tone="text-primary"})=><div className="flex items-center gap-3 rounded-md border bg-card p-4"><span className={`rounded-md bg-muted p-2 ${tone}`}><Icon className="h-5 w-5"/></span><div><p className="text-[11px] font-semibold uppercase text-muted-foreground">{label}</p><p className="text-xl font-bold">{value ?? "—"}</p></div></div>;

export function ManagementReports(){
 const [draft,setDraft]=useState(initial),[filters,setFilters]=useState(initial),[state,setState]=useState({loading:true,error:"",data:null}),[exporting,setExporting]=useState("");
 useEffect(()=>{let active=true;setState(s=>({...s,loading:true,error:""}));getManagementReports(filters).then(r=>active&&setState({loading:false,error:"",data:r.data})).catch(e=>active&&setState({loading:false,error:e.message,data:null}));return()=>{active=false}},[filters]);
 const data=state.data||{}, summary=data.summary||{}, options=data.options||{}, pagination=data.pagination||{page:1,pageSize:20,total:0,totalPages:0};
 const submit=e=>{e.preventDefault();if(draft.dateFrom&&draft.dateTo&&draft.dateFrom>draft.dateTo){setState(s=>({...s,error:"Date From must not be after Date To."}));return}setFilters({...draft,page:1})};
 const doExport=async format=>{setExporting(format);try{await exportManagementReport(format,filters)}catch(e){setState(s=>({...s,error:e.message}))}finally{setExporting("")}};
 const paymentData=useMemo(()=>data.payment_distribution||[],[data.payment_distribution]);
 return <div className="flex-1 overflow-auto bg-slate-50 p-4 print:bg-white">
  <div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs text-muted-foreground">Modules &gt; Reports &amp; Analytics</p><h1 className="text-2xl font-bold">Reports &amp; Analytics</h1></div><div className="flex gap-2 print:hidden"><button onClick={()=>doExport("pdf")} disabled={!!exporting} className="flex items-center gap-2 rounded bg-emerald-600 px-3 py-2 text-sm text-white"><Download className="h-4 w-4"/>Export PDF</button><button onClick={()=>doExport("excel")} disabled={!!exporting} className="flex items-center gap-2 rounded bg-blue-600 px-3 py-2 text-sm text-white"><FileSpreadsheet className="h-4 w-4"/>Export Excel</button><button onClick={()=>window.print()} className="rounded border bg-card px-3 py-2 text-sm">Print</button></div></div>
  <Card title="Filters" className="mb-4 print:hidden"><form onSubmit={submit} className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{[["Date From","dateFrom","date"],["Date To","dateTo","date"]].map(([l,k,t])=><label key={k} className="text-xs font-medium">{l}<input type={t} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})} className="mt-1 w-full rounded border bg-background px-2 py-2"/></label>)}
   {[["Cargo Status","cargoStatus",options.cargo_statuses],["Customs Status","customsStatus",options.customs_statuses],["Payment Status","paymentStatus",options.payment_statuses],["Cargo Type","cargoType",options.cargo_types]].map(([l,k,items])=><label key={k} className="text-xs font-medium">{l}<select value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})} className="mt-1 w-full rounded border bg-background px-2 py-2"><option value="">All</option>{(items||[]).map(x=><option key={x}>{x}</option>)}</select></label>)}
   <div className="flex items-end gap-2"><button className="flex flex-1 items-center justify-center gap-1 rounded bg-emerald-600 px-3 py-2 text-sm text-white"><Search className="h-4 w-4"/>Search</button><button type="button" onClick={()=>{setDraft(initial);setFilters(initial)}} className="rounded bg-amber-500 p-2"><X className="h-4 w-4"/></button></div></form></Card>
  {state.error&&<div className="mb-4"><ErrorState message={state.error}/></div>}
  <div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Total Cargo" value={state.loading?"…":summary.total_cargo} icon={Boxes}/><Kpi label="Storage Occupied" value={state.loading?"…":summary.storage_occupied==null?"—":`${summary.storage_occupied}%`} icon={Boxes} tone="text-emerald-600"/><Kpi label="Pending Customs" value={state.loading?"…":summary.pending_customs} icon={AlertTriangle} tone="text-amber-600"/><Kpi label="Verified Revenue" value={state.loading?"…":money(summary.total_revenue)} icon={CircleDollarSign} tone="text-emerald-600"/><Kpi label="Outstanding / Unpaid" value={state.loading?"…":money(summary.outstanding)} icon={CircleDollarSign} tone="text-red-600"/></div>
  <div className="mb-4 grid gap-4 xl:grid-cols-2"><ChartCard title="Cargo Movement" empty={!data.cargo_movement?.length}><ResponsiveContainer><LineChart data={data.cargo_movement}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="period"/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Line type="monotone" dataKey="inbound" stroke="#1976d2"/><Line type="monotone" dataKey="outbound" stroke="#32b45f"/></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Revenue by Cargo Type" empty={!data.revenue_by_cargo_type?.length}><ResponsiveContainer><BarChart data={data.revenue_by_cargo_type}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="cargo_type"/><YAxis/><Tooltip formatter={money}/><Bar dataKey="revenue" fill="#1976d2"/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Storage Utilization by Zone" empty={!data.storage_utilization?.some(x=>Number(x.occupied_bins))}><ResponsiveContainer><PieChart><Pie data={data.storage_utilization} dataKey="occupied_bins" nameKey="zone" outerRadius={90} label>{data.storage_utilization?.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></ChartCard><ChartCard title="Payment Status Distribution" empty={!paymentData.length}><ResponsiveContainer><PieChart><Pie data={paymentData} dataKey="count" nameKey="status" innerRadius={55} outerRadius={90} label>{paymentData.map((_,i)=><Cell key={i} fill={colors[(i+1)%colors.length]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></ChartCard></div>
  <div className="grid gap-4 xl:grid-cols-[minmax(0,3fr)_minmax(260px,1fr)]"><Card title="Cargo Records"><div className="p-3"><input value={draft.search} onChange={e=>setDraft({...draft,search:e.target.value})} onKeyDown={e=>e.key==="Enter"&&setFilters({...draft,page:1})} placeholder="Search cargo, invoice or payment reference…" className="mb-3 w-full rounded border px-3 py-2 text-sm md:max-w-sm"/><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-muted"><tr>{["Cargo Reference","Cargo Status","Location","Customs","Invoice","Paid Amount","Outstanding","Registration Date"].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{state.loading?<tr><td colSpan="8" className="p-8 text-center">Loading report records…</td></tr>:!data.cargo?.length?<tr><td colSpan="8" className="p-8 text-center text-muted-foreground">No cargo records found for the selected filters.</td></tr>:data.cargo.map(r=><tr key={r.cargo_reference} className="border-t"><td className="p-2 font-semibold">{r.cargo_reference}</td><td className="p-2">{r.cargo_status}</td><td className="p-2">{r.current_location||"—"}</td><td className="p-2">{r.customs_status||"—"}</td><td className="p-2">{r.invoice_status}</td><td className="p-2">{money(r.paid_amount)}</td><td className="p-2">{money(r.outstanding_amount)}</td><td className="p-2">{new Date(r.registration_date).toLocaleDateString()}</td></tr>)}</tbody></table></div>{pagination.total>0&&<PaginationControls page={pagination.page} pageSize={pagination.pageSize} total={pagination.total} onPageChange={page=>setFilters({...filters,page})} onPageSizeChange={pageSize=>setFilters({...filters,page:1,pageSize})} itemLabel="cargo records"/>}</div></Card>
   <Card title="Alerts"><div className="space-y-3 p-3">{[["Customs Backlog",data.alerts?.customs_backlog,"Cargo awaiting Customs action."],["Bins At Capacity",data.alerts?.bins_at_capacity,"Bins that reached a configured physical limit."],["Outstanding Invoices",data.alerts?.outstanding_invoices,"Non-cancelled invoices with a balance."],["Release Blockers",data.alerts?.blocked_releases,"Cargo blocked by central release-readiness rules."]].map(([t,n,d])=><div key={t} className="rounded border-l-4 border-amber-500 bg-amber-50 p-3"><div className="flex justify-between font-semibold"><span>{t}</span><span>{n??"…"}</span></div><p className="mt-1 text-xs text-muted-foreground">{d}</p></div>)}</div></Card></div>
 </div>
}
