import { useEffect, useState } from "react";
import { ClipboardList, BarChart3, LogOut, UserCircle2 } from "lucide-react";
import { Navigate, NavLink, Route, Routes, useNavigate } from "react-router-dom";
import { DataTable, ErrorState, PageHeader, SectionCard } from "@/components/wms/OperationalUi";
import { AccountProfilePage } from "@/components/wms/ProfilePage";
import { HeaderActions } from "@/components/wms/HeaderActions";
import { getAuditLogs, getManagementReports, logout } from "@/services/api";

const nav=[{label:"Audit History",icon:ClipboardList,to:"/auditor"},{label:"Reports",icon:BarChart3,to:"/auditor/reports"},{label:"Profile",icon:UserCircle2,to:"/auditor/profile"}];
function AuditHistory(){const [state,setState]=useState({rows:[],error:"",loading:true});useEffect(()=>{getAuditLogs({limit:500}).then(r=>setState({rows:r.data||[],error:"",loading:false})).catch(e=>setState({rows:[],error:e.message,loading:false}));},[]);return <><PageHeader eyebrow="Auditor" title="Immutable Audit History" description="Read-only active and archived system events."/><div className="flex-1 overflow-auto p-4"><SectionCard title="Audit Events">{state.error&&<ErrorState message={state.error}/>}<DataTable loading={state.loading} rows={state.rows} columns={[{key:"created_at",label:"Time"},{key:"action",label:"Action"},{key:"module",label:"Module"},{key:"username",label:"Actor"},{key:"description",label:"Description"},{key:"is_archived",label:"Archived"}]}/></SectionCard></div></>}
function Reports(){const [state,setState]=useState({data:{},error:"",loading:true});useEffect(()=>{getManagementReports().then(r=>setState({data:r.data||{},error:"",loading:false})).catch(e=>setState({data:{},error:e.message,loading:false}));},[]);return <><PageHeader eyebrow="Auditor" title="Compliance Reports" description="Read-only operational and financial summaries."/><div className="p-4">{state.error&&<ErrorState message={state.error}/>}<SectionCard title="Invoices by Status"><DataTable loading={state.loading} rows={state.data.invoices_by_status||[]} columns={[{key:"status",label:"Status"},{key:"invoice_count",label:"Count"},{key:"total_amount",label:"Total"}]}/></SectionCard></div></>}
export default function AuditorPortal(){const navigate=useNavigate();return <div className="flex h-screen bg-background"><aside className="flex w-64 flex-col border-r bg-sidebar text-sidebar-foreground"><div className="border-b p-4"><div className="text-xs uppercase opacity-60">Auditor</div><div className="font-semibold">Compliance Console</div></div><nav className="flex-1 py-2">{nav.map(i=><NavLink key={i.to} to={i.to} end={i.to==="/auditor"} className="flex items-center gap-3 px-4 py-2.5 text-sm hover:bg-sidebar-accent"><i.icon className="h-4 w-4"/>{i.label}</NavLink>)}</nav><button className="m-3 flex items-center justify-center gap-2 rounded border p-2 text-xs" onClick={async()=>{await logout();navigate("/");}}><LogOut className="h-4 w-4"/>Exit</button></aside><div className="flex min-w-0 flex-1 flex-col"><header className="flex h-14 items-center justify-between bg-header px-5 text-header-foreground"><span className="font-semibold">Fumba Port WMS</span><HeaderActions/></header><Routes><Route index element={<AuditHistory/>}/><Route path="logs" element={<AuditHistory/>}/><Route path="reports" element={<Reports/>}/><Route path="profile" element={<AccountProfilePage/>}/><Route path="*" element={<Navigate to="/auditor" replace/>}/></Routes></div></div>}
