import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, CreditCard, LoaderCircle, LockKeyhole, RefreshCw, ShieldCheck } from "lucide-react";
import { useParams } from "react-router-dom";
import { createPublicPaymentAttempt, getPublicPaymentAttempt, getPublicPaymentSummary } from "../services/api";

const money=(value,currency="TZS")=>new Intl.NumberFormat("en-TZ",{style:"currency",currency,maximumFractionDigits:2}).format(Number(value||0));
const fieldClass="h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm outline-none transition focus:border-sky-600 focus:ring-2 focus:ring-sky-100";
const errorText=(error)=>error?.message||"The request could not be completed.";

export default function PublicPayment(){
  const {token}=useParams();
  const [state,setState]=useState({loading:true,error:"",summary:null});
  const [form,setForm]=useState({amount:"",name:"",email:"",phone:"",country_code:"255",network:""});
  const [attempt,setAttempt]=useState(null); const [submitting,setSubmitting]=useState(false); const [formError,setFormError]=useState("");
  const load=useCallback(async()=>{setState(current=>({...current,loading:true,error:""}));try{const response=await getPublicPaymentSummary(token);setState({loading:false,error:"",summary:response.data});setForm(current=>({...current,amount:response.data.available_to_pay}));}catch(error){setState({loading:false,error:errorText(error),summary:null});}},[token]);
  useEffect(()=>{load();},[load]);
  useEffect(()=>{if(!attempt?.attempt_reference||!["PENDING","PROCESSING","NOT_INITIATED"].includes(attempt.status))return undefined;const timer=setInterval(async()=>{try{const response=await getPublicPaymentAttempt(token,attempt.attempt_reference);const data=response.data;setAttempt(current=>({...current,status:data.gateway_status,reconciliation_status:data.reconciliation_status,verified_at:data.verified_at,failure_reason:data.failure_reason}));if(!["PENDING","PROCESSING","NOT_INITIATED"].includes(data.gateway_status))load();}catch{}},4000);return()=>clearInterval(timer);},[attempt?.attempt_reference,attempt?.status,load,token]);
  const submit=async(event)=>{event.preventDefault();setFormError("");const amount=Number(form.amount),available=Number(state.summary?.available_to_pay||0);if(!Number.isFinite(amount)||amount<=0){setFormError("Enter an amount greater than zero.");return}if(amount>available){setFormError("The amount cannot exceed the currently available balance after pending payments.");return}setSubmitting(true);try{const response=await createPublicPaymentAttempt(token,form);setAttempt(response.data);}catch(error){setFormError(errorText(error));}finally{setSubmitting(false)}};
  if(state.loading)return <Shell><div className="flex min-h-[360px] items-center justify-center"><LoaderCircle className="h-8 w-8 animate-spin text-sky-700"/><span className="ml-3 text-sm text-slate-600">Loading payment details…</span></div></Shell>;
  if(state.error)return <Shell><div className="mx-auto max-w-md py-16 text-center"><LockKeyhole className="mx-auto h-12 w-12 text-slate-400"/><h2 className="mt-4 text-xl font-bold text-slate-900">Payment link unavailable</h2><p className="mt-2 text-sm text-slate-600">{state.error}</p><button onClick={load} className="mt-6 rounded-lg bg-sky-700 px-4 py-2 text-sm font-semibold text-white">Try again</button></div></Shell>;
  const summary=state.summary;const complete=Number(summary.outstanding_balance)<=0;
  return <Shell><div className="grid gap-6 lg:grid-cols-[1.05fr_.95fr]">
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
      <div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-sky-700">Cargo Payment</p><h1 className="mt-2 text-2xl font-bold text-slate-950">Payment summary</h1></div><ShieldCheck className="h-9 w-9 text-emerald-600"/></div>
      <dl className="mt-6 grid gap-4 sm:grid-cols-2">{[["Cargo Reference",summary.cargo_reference],["Invoice Reference",summary.invoice_reference],["Payment Reference",summary.payment_reference],["Current Status",summary.financial_status]].map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-4"><dt className="text-xs font-medium text-slate-500">{label}</dt><dd className="mt-1 break-all font-semibold text-slate-900">{value}</dd></div>)}</dl>
      <div className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-4"><Amount label="Invoice Total" value={summary.invoice_total} currency={summary.currency}/><Amount label="Verified Paid" value={summary.total_verified_paid} currency={summary.currency}/><Amount label="Pending / Reserved" value={summary.pending_reserved} currency={summary.currency}/><Amount label="Available to Pay" value={summary.available_to_pay} currency={summary.currency} strong/></div><p className="mt-3 text-xs text-slate-500">Remaining balance: {money(summary.outstanding_balance,summary.currency)}</p>
      <p className="mt-5 flex items-center gap-2 text-xs text-slate-500"><LockKeyhole className="h-4 w-4"/>This secure link is limited to this payment obligation.</p>
    </section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
      {complete?<div className="py-10 text-center"><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-600"/><h2 className="mt-4 text-2xl font-bold text-slate-950">Payment Complete</h2><p className="mt-2 text-sm text-slate-600">This invoice is fully paid. No further payment is required.</p></div>:<><div className="flex items-center gap-3"><CreditCard className="h-7 w-7 text-sky-700"/><div><h2 className="font-bold text-slate-950">Pay an installment</h2><p className="text-xs text-slate-500">Choose any amount up to the remaining balance.</p></div></div>
      <form onSubmit={submit} className="mt-5 space-y-4"><Field label="Amount to Pay Now"><input className={fieldClass} type="number" min="0.01" step="0.01" max={summary.available_to_pay} value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/></Field><Field label="Name"><input className={fieldClass} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></Field><Field label="Email"><input className={fieldClass} type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></Field><div className="grid gap-4 sm:grid-cols-[92px_1fr]"><Field label="Code"><input className={fieldClass} value={form.country_code} onChange={e=>setForm({...form,country_code:e.target.value})} required/></Field><Field label="Phone"><input className={fieldClass} inputMode="tel" placeholder="7XXXXXXXX" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required/></Field></div><Field label="Mobile Money"><select className={fieldClass} value={form.network} onChange={e=>setForm({...form,network:e.target.value})} required><option value="">Select network</option><option value="vodacom">M-Pesa</option><option value="airtel">Airtel Money</option><option value="tigo">Mixx by Yas</option><option value="halotel">HaloPesa</option></select></Field>{formError&&<p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{formError}</p>}<button disabled={submitting||Number(summary.available_to_pay)<=0} className="flex h-11 w-full items-center justify-center rounded-lg bg-sky-700 px-4 text-sm font-bold text-white hover:bg-sky-800 disabled:opacity-60">{submitting?<><LoaderCircle className="mr-2 h-4 w-4 animate-spin"/>Starting payment…</>:"Pay Now"}</button><p className="text-center text-xs text-slate-500">Your mobile-money PIN is entered only in Flutterwave’s provider authorization flow. Fumba Port WMS never asks for or stores it.</p></form></>}
      {attempt&&<div className="mt-5 rounded-xl border border-sky-200 bg-sky-50 p-4 text-sm"><div className="flex items-center justify-between"><span className="font-semibold text-slate-900">Attempt {attempt.attempt_reference}</span><button onClick={load} aria-label="Refresh payment summary"><RefreshCw className="h-4 w-4 text-sky-700"/></button></div><p className="mt-2 text-slate-600">Status: <strong>{attempt.status}</strong></p>{attempt.failure_reason&&<p className="mt-1 text-rose-700">{attempt.failure_reason}</p>}{attempt.next_action?.payment_instruction?.note&&<p className="mt-2 text-slate-700">{attempt.next_action.payment_instruction.note}</p>}{attempt.next_action?.redirect_url?.url&&<a className="mt-3 flex h-11 items-center justify-center rounded-lg bg-sky-700 px-4 font-bold text-white hover:bg-sky-800" href={attempt.next_action.redirect_url.url} target="_blank" rel="noreferrer">Continue to Flutterwave Sandbox Authorization</a>}</div>}
    </section>
  </div></Shell>;
}

function Shell({children}){return <main className="min-h-screen bg-gradient-to-br from-slate-100 via-white to-sky-50 px-4 py-6 sm:px-6 sm:py-10"><div className="mx-auto max-w-5xl"><header className="mb-6 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-sky-700 font-black text-white">FP</div><div><p className="font-bold text-slate-950">Fumba Port Warehouse Management System</p><p className="text-xs text-slate-500">Secure customer payments</p></div></header>{children}<footer className="mt-8 text-center text-xs text-slate-500">Fumba Port WMS · Secure installment payment</footer></div></main>}
function Amount({label,value,currency,strong}) {return <div className={`rounded-xl border p-4 ${strong?"border-sky-200 bg-sky-50":"border-slate-200"}`}><p className="text-xs text-slate-500">{label}</p><p className={`mt-1 ${strong?"text-lg font-extrabold text-sky-800":"font-bold text-slate-900"}`}>{money(value,currency)}</p></div>}
function Field({label,children}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-700">{label}</span>{children}</label>}
